#!/usr/bin/env bash

# Parameters for soil subset
./metacherchant.sh --tool environment-finder \
        --k 31 \
        --coverage=5 \
        --reads /home/AAFC-AAC/leecat/catrione_metagenomics/soil/SSR*{1,2}.fastq.gz \
        --seq /home/AAFC-AAC/leecat/iceberg.fasta \
        --output subset_soil/output \
        --work-dir subset_soil/workDir \
        --maxkmers=100000 \
        --bothdirs=TRUE \
        --chunklength=100 \
        -pf 5\
        -m 500G \
        -c
