#!/usr/bin/env bash

./metacherchant.sh --tool environment-finder \
        --k 31 \
        --coverage=5 \
        --reads /home/AAFC-AAC/leecat/catrione_metagenomics/SRR6512893_*{1,2}.fastq.gz \
        --seq /home/AAFC-AAC/leecat/ICE_seq_all.fas \
        --output subset/SRR6512893_v2/output \
        --work-dir subset/SRR6512893_v2/workDir \
        --maxkmers=100000 \
        --bothdirs=TRUE \
        --chunklength=100 \
        -pf 5\
        -m 100G \
        -c
